### ISSUE TITLE
How to execute?

### ISSUE THREAD

**Issue by IcaroBichir** [onebithq/jenkins-bitbucket-pullrequest#1]
I've already configure the variables, but how I initiate the scrip on Jenkins?

**Comment by akhy** [comment]
Sorry for the lack of documentations. This project is pretty much WIP but functional enough for our uses. 

We'll add the documentation shortly :smile:

**Comment by akhy** [comment]
Added setup instruction to the README. 

Feel free to reopen if you have any questions.
